stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker pull registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.10.0 && PULL_RESULT="ok"
    - if [ "$PULL_RESULT" == "ok" ]; then echo '拉取完成'; else echo '拉取失败' && xxxx; fi
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker tag registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.10.0 $DOCKER_USERNAME/prometheus-adapter:v0.10.0
    - docker images
    - docker push $DOCKER_USERNAME/prometheus-adapter:v0.10.0
